version: "3"
services:
  northstar-attrition:
    image: nsmp-custom
    pull_policy: always
    environment:
      NS_PORT: 37015
      # uncomment for Northstar v1.12 and older
      #NS_PORT_AUTH: 8081
      NS_SERVER_NAME: "[REGION] SERVER NAME HERE"
      NS_SERVER_DESC: "Server description here!"
      NS_EXTRA_ARGUMENTS: |
        +setplaylist private_match
        +mp_gamemode fd_easy
        +map mp_homestead
        +ns_server_password ""
        +ns_private_match_countdown_length 0
        +ns_should_return_to_lobby 0
        +ns_auth_allow_insecure 1
        +net_compresspackets_minsize 64
        +net_compresspackets 1
        +spewlog_enable 0
        +sv_maxrate 127000
    volumes:
      - /media/files/titanfall2:/mnt/titanfall:ro
      - /media/files/mods:/mnt/mods:ro
    ports:
      - "37015:37015/udp"
    restart: "unless-stopped"
